### ISSUE TITLE
No issue, just a thank you

### ISSUE THREAD

**Issue by bitpixl** [crssi/Firefox#1]
Hi Crssi,

Once again I found my solution here on your firefox github page :+1: 

My problem was with reddit.com not loading videos because of the p.o.o.p. extension and having no clue on how to examine the browser console.

thanks man and keep up the great work.

(p.s. there was someone else on the p.o.o.p. github page asking about reddit, perhaps you can help out?)

**Comment by crssi** [comment]
I am happy to help you out., even I do not remember exact problem.

> (p.s. there was someone else on the p.o.o.p. github page asking about reddit, perhaps you can help out?)

Do you have any direct link?

**Comment by bitpixl** [comment]
I was wrong the comment about reddit is on the firefox extension site:

[P.O.O.P. Firefox Extension](https://addons.mozilla.org/en-US/firefox/addon/privacy-oriented-origin-policy/reviews/)

I would love if you could provide an how to (solve these kind of issues), so perhaps I'm able to solve it myself in the future. Actually there should be an howto on the github p.o.o.p. wiki ;)

**Comment by crssi** [comment]
I see. I am afraid that I cannot make an reply on FF extension page, since I am not author/submitter.

Cheers
