### ISSUE TITLE
WebGL Fingerprint Defender / WE Canvasblocker?

### ISSUE THREAD

**Issue by bitpixl** [crssi/Firefox#2]
Hi Crssi,

As always I'm checking your user.js/addon settings from time to time and noticed the other day you had some extra settings for WebGL. In your latest change you changed:

`do not use without "WebGL Fingerprint Defender" WE`

to

`should be true, except if using WE CanvasBlocker`

Is this still the same addon or are you using a setting in Canvasblocker now?

Thanks and keep up the great work!

**Comment by crssi** [comment]
Thank you for asking... and using "my template". 😄 

`CanvasBlocker` now covers WebGL and that makes `WebGL Fingerprint Defender` redundant. 😉 
That is also why `WebGL Fingerprint Defender` is removed from my "user.js".

Feel free to close this issue when appropriate.

Cheers

**Comment by bitpixl** [comment]
good to know! thanks buddy 👍

**Comment by RakeshAllikatti** [comment]
How do I get the manifest file?

**Comment by crssi** [comment]
Which manifest file?
Do you mean manifest file of any web extension or?
