### ISSUE TITLE
[fix] smart referer whitelist format incorrect

### ISSUE THREAD

**Issue by bitpixl** [crssi/Firefox#6]
Hi Crssi,

hope all is well :)
I just found out that the way you've formatted the smart referer whitelist is not the way smart referer expects it to be.

if you add your whitelist to smart referer and then keep an eye on the debug tab in the browser console while trying to load icloud.com (and failing ofc), you'll see that it's still rejecting the http referers.

the correct format should be like the default whitelist:
`.apple.com>.*apple*.* .google*.*>.google*.* .google*.*>.gstatic.com .google*.*>.ytimg.com .icloud.com>.*apple*.* .paloaltonetworks.com>.cloudfront.net .travelriskmap.com>*`

cheers!

edit: fixed typo

**Comment by crssi** [comment]
Thank you. Appreciated. 😄 

One question... the missing dot `.` at start is typo or intentional?

Cheers

**Comment by bitpixl** [comment]
your welcome, glad I could help you out for once ;) And definitely a typo! (fixed it)

**Comment by crssi** [comment]
I have corrected the problem accordingly.

Thank you again and cheers ❤️
