### ISSUE TITLE
2 minor problems

### ISSUE THREAD

**Issue by pepeja** [crssi/Firefox#8]
Not sure if you know this already but profile.zip is broken and you cannot solve recaptchas with your ublock backup (might be intentional) 
I appreciate your work long time user

**Comment by crssi** [comment]
Thank you @pepeja 

Can you provide an URL of the recaptcha so I have a sample to work on.

Which is the 2nd minor problem?

Cheers

**Comment by pepeja** [comment]
https://patrickhlauke.github.io/recaptcha/ 
2nd thing was just that your profile.zip is broken it doesnt have any of the necessary files its just a bunch of folders with nothing in it

**Comment by crssi** [comment]
I see. I was actually just this specific recaptcha test/demo site that it didn't work, otherwise it worked.
But, anyway, your post shed some light to my unbreak list which bothered me and I have corrected now.
This site should also work now, due to specific exception.

To speed-up a process, do a reload of `crssi: Unbreak` list and you will be good:
![Capture](https://user-images.githubusercontent.com/17024151/89619108-ece20080-d87c-11ea-9531-2b6abf8d4c7a.PNG)

**Comment by crssi** [comment]
About profile.zip... I see it OK, locally and on GitHub, so I really do not know why, but the culprit must be at your end.

Thank you again for a report.

Cheers

**Comment by pepeja** [comment]
oh no it wasn't just the test site it was all sites (2) that I'm supposed to encounter the recaptcha but it you have to do specific exceptions for every site then its probably best for me to just disable ublock upon encountering them. 

regarding the profile it might be because I'm on linux (new to linux so ill just blame it on that) but if I go to a previous version of your profile.zip everything is fine but i guess it might be on my end. didn't mean to close but this issue (new to github as well) is basically done anyways.

**Comment by crssi** [comment]
> oh no it wasn't just the test site it was all sites (2) that I'm supposed to encounter the recaptcha

That is strange, but I can have something generally wrong.
When you encounter such site next time, or you have some more already, please, let me know, so I can tune it broadly.

Thank you and cheers

**Comment by pepeja** [comment]
well the sites far I've seen it not working are 
upon creating an account here https://mail.protonmail.com/create/new (which isnt reliable) and https://signup.na.leagueoflegends.com/ (you should see protected by recaptcha in the bottom right corner) of course its not really necessary to make a specific exception for these I just presumed that all recaptchas were broken. I realize now this might not be true since this other test site works https://www.google.com/recaptcha/api2/demo (unless that's different) and it might be better for privacy to not have them work (?) but I just was bringing it to your attention since it was the only surface level "issue" I've seen. As always thank you for this wonderful project. side note: there are also other very minor problems like ads on reddit but I wouldn't want you to change things to accommodate for me since its your profile of course.

**Comment by crssi** [comment]
Thank you @pepeja 
Now it should work https://github.com/crssi/Firefox/commit/909fc7ceafd3485fb6821709ec1a68b5b468b119#diff-38a1da6018946add57903ac19fdbc1a1

Please, if you find anything, just let me know.

Cheers
